### ISSUE TITLE
Unraid installation

### ISSUE THREAD

**Issue by ktfcaptain** [superstreamerapp/superstreamer#119]
I've installed all 4 parts on my Unraid server but they won't start because I still need to copy the sample .env.....but I can't find the filepath for any of this anywhere.  Nothing new in /mnt/user/appdata and none of the templates seem to have any entries for this.

I feel like I'm losing my mind today, Google says 0 results when I search but Bing pulls up 4 pages....wtf......

**Comment by matvp91** [comment]
Create a new folder and a new file named `docker-compose.yml` in that folder. Paste in the contents from https://superstreamer.xyz/guide/getting-started.html.

Create a `config.env` in the same folder (the one you created earlier), with the required env variables. If you don't want to self host your S3, use [Cloudflare R2](https://www.cloudflare.com/developer-platform/products/r2/), they have a very generous free tier for you to play with.

As for unraid, we support no official template (it's community driven) and I have no idea how up-to-date it is.
