### ISSUE TITLE
Add preroll support to live with Stitcher

### ISSUE THREAD

**Issue by Ale1x** [superstreamerapp/superstreamer#121]
**Is your feature request related to a problem? Please describe.**
Currently, streaming platforms lack a convenient way to add preroll content using stitcher technology, which limits content creators' ability to include introductory or promotional materials seamlessly.

**Describe the solution you'd like**
Implement native support for preroll integration using stitcher, allowing to:

- Easily add preroll content before the main stream
- Dynamically insert promotional or introductory segments
- Maintain smooth playback and seamless transition to primary content

**Describe alternatives you've considered**
- Manual video editing to insert preroll content
- Third-party tools for video preprocessing

**Additional context**
- This feature would enhance content flexibility
- Improves viewer engagement through customizable stream introductions
- Streamlines content creation workflow for creators

**Comment by matvp91** [comment]
Added in https://github.com/superstreamerapp/superstreamer/commit/495841186c1779ee8d0a41c2c1f06afcff6cbf7e
